export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    EDIT_SELECTED_PRODUCT: "EDIT_SELECTED_PRODUCT",
}